config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 3000 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name, case_sensitive: false
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { minimum: 0, maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]


  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
      @article = Article.new(article_params)
      @article.user = current_user
    if @article.save
      flash[:notice] = "Post Successful!"
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Update Successful!"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was created successfully"
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
    session[:user_id]= user.id
    flash[:notice] = "You have logged in successfully"
    redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index, :new, :create]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "You account info was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id]= @user.id
      flash[:notice] = "Welcome to Spiky's blog #{@user.username}! You have successfully signed up!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
  end


  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own profile"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow p-0 mb-5 bg-dark rounded">
        <div class="card-header", id= "card-header">
          <% if article.user %>
            by <%= link_to article.user.username, user_path(article.user)  %>
          <% end %>
          <% if article.categories.any? %>
            <div class="mt-2">
              <%= render article.categories %>
            </div>
          <% end %>
        </div>
        <div class="card-body", id= "card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-decoration-none text-reset fw-bold" %></h5>
          <hr>
          <p class="card-text"><%= truncate(article.description, length: 100) %></p>
          <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
          <% if logged_in? && (article.user == current_user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
        </div>
        <div class="card-footer text-muted", id= "card-footer">
          <small>Created <%= time_ago_in_words(article.created_at) %> ago,
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/articles/_edit_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow-lg p-3 mb-4 bg-info rounded", local: true) do |f| %>
        <div class="mb-3 row">
          <%= f.label :title, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="mb-3 row">
          <%= f.label :description, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>
        
        <div class="mb-3 row">
          <%= f.label :category, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.collection_select(:category_ids, Category.all, :id, :name, { prompt: "Make your selection from the list below (can be empty)"}, {multiple: true, size: 3, class: "form-select shadow rounded" } ) %>
          </div>
        </div>

        <div class="mb-3 text-center">
          <%= f.submit class: "btn btn-dark btn-lg"%>
        </div>

      <% end %>
    </div>

    <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info text-center" %>
  </div>
</div>

app/views/articles/_new_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-4 bg-primary rounded", local: true) do |f| %>
        <div class="mb-3 row">
          <%= f.label :title, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="mb-3 row">
          <%= f.label :description, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="mb-3 row">
          <%= f.label :category, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.collection_select(:category_ids, Category.all, :id, :name, { prompt: "Make your selection from the list below (can be empty)"}, {multiple: true, size: 3, class: "form-select shadow rounded" } ) %>
          </div>
        </div>

        <div class="mb-3 text-center">
          <%= f.submit class: "btn btn-dark btn-lg"%>
        </div>

      <% end %>
    </div>

    <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-primary text-center" %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4 text-white">Edit article</h1>
<%= render 'edit_form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4 text-white">All articles</h1>

<div class="flickr_pagination">
  <%= will_paginate @articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

<%= render 'article' %>

<div class="flickr_pagination">
  <%= will_paginate @articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4 text-white">Create a new article</h1>
  <%= render 'new_form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4 text-white"><%= @article.title %></h2>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow p-0 mb-5 bg-dark rounded">
        <div class="card-header", id= "card_header">
          by <%= @article.user.username if @article.user %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
          <% if @article.categories.any? %>
            <div class="mt-2">
              <%= render @article.categories %>
            </div>
          <% end %>
        </div>
        <div class="card-body", id="card-body">
          <div class="card-text text-start"><%= simple_format(@article.description) %></div>
          <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-info" %>
            <%= link_to "Delete", article_path(@article), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
        </div>
        <div class="card-footer", id= "card_footer">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
    <div class="text-center">
      <%= link_to 'Cancel and return to articles listing', articles_path, class: "btn btn-outline-light" %><br>
    </div>

  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "text-decoration-none text-dark badge rounded-pill bg-success" %>

app/views/categories/_edit_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_with(model: @category, class: "shadow p-3 mb-4 bg-info rounded", local: true) do |f| %>
  <div class="mb-3 row">
    <%= f.label :name, "Category", class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
    </div>
  </div>

  <div class="mb-3 text-center">
    <%= f.submit class: "btn btn-dark btn-lg"%>
  </div>

<% end %>

app/views/categories/_new_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_with(model: @category, class: "shadow p-3 mb-4 bg-primary rounded", local: true) do |f| %>
  <div class="mb-3 row">
    <%= f.label :name, "Category", class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
    </div>
  </div>

  <div class="mb-3 text-center">
    <%= f.submit class: "btn btn-dark btn-lg"%>
  </div>

<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4 text-white">Edit category</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'edit_form' %>
    </div>

    <%= link_to '[ Cancel and return to categories listing ]', category_path(@category), class: "text-primary text-center" %>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center text-white mt-4">Categories</h1>

<div class="flickr_pagination">
  <%= will_paginate @categories, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

<div class="container">
  <% @categories.each do |category| %>
  <div class="row justify-content-md-center">
    <div class="col-4 mt-4">
      <div class="card text-center shadow p-0 mb-5 bg-dark rounded">
        <div class="card-body", id= "card-body">
          <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-decoration-none text-reset fw-bold" %></h5>
          <hr>
          <%= pluralize(category.articles.count, "article") %>
        </div>
        <div class="card-footer text-muted", id= "card-footer">
          <small>Created <%= time_ago_in_words(category.created_at) %> ago,
            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

<div class="flickr_pagination">
  <%= will_paginate @categories, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4 text-white">Create a new category</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'new_form' %>
    </div>

    <%= link_to '[ Cancel and return to categories listing ]', categories_path, class: "text-primary text-center" %>
  </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4 text-white">Category: <%= @category.name%></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4 text-white"><%= pluralize(@category.articles.count, "Article") %></h3>

<div class="flickr_pagination">
  <%= will_paginate @articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination">
  <%= will_paginate @articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "DuckDuckGo", "https://DuckDuckGo.com", class: "text-white-50" %></small>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon btn btn-light"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Profiles", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? && current_user.admin? %>
            <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
            <li><hr class="dropdown-divider"></li>
            <% end %>
            <%= link_to "All Categories", categories_path, class: "dropdown-item" %>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? %>
            <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "View articles", articles_path, class: "dropdown-item" %>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %> <%= current_user.username %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
              <li><hr class="dropdown-divider"></li>
              <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log in', login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/pages/home.html.erb
<div class="container" id='home-container'>
  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active" id='first_pic'>
        <img src="" class="d-block w-100" alt="">
        <div class="carousel-caption d-none d-md-block">
          <h5>First and foremost!</h5>
          <p>The day will come when this is actually something that works!</p>
        </div>
      </div>
      <div class="carousel-item" id='second_pic'>
        <img src="" alt="">
        <div class="carousel-caption d-none d-md-block">
          <h5>Secondly becondly</h5>
          <p>This will probably be cool too!</p>
        </div>
      </div>
      <div class="carousel-item" id=third_pic>
        <img src="" alt="">
        <div class="carousel-caption d-none d-md-block">
          <h5>Thirdthstly, it will be chaos incarnate!</h5>
          <p>You read that right, thirdthstly.</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <div class= "text-center">
    <%= link_to 'Sign up!', signup_path, class: "btn btn-success" %>
    </div>
</div>

app/views/users/_edit_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-4 bg-info rounded", local: true) do |f| %>
        <div class="mb-3 row">
          <%= f.label :username, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>

        <div class="mb-3 row">
          <%= f.label :email, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>

        <div class="mb-3 row">
          <%= f.label :password, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
          </div>
        </div>

        <div class="mb-3 text-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-dark btn-lg") %>
        </div>

      <% end %>
    </div>

    <%= link_to '[ Cancel and return to users listing ]', users_path, class: "text-primary text-center" %>
  </div>
</div>

app/views/users/_new_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-4 bg-primary rounded", local: true) do |f| %>
        <div class="mb-3 row">
          <%= f.label :username, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>

        <div class="mb-3 row">
          <%= f.label :email, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>

        <div class="mb-3 row">
          <%= f.label :password, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
          </div>
        </div>

        <div class="mb-3 text-center">
          <%= f.submit "Sign up", class: "btn btn-dark btn-lg"%>
        </div>

      <% end %>
    </div>

    <%= link_to '[ Cancel and return to users listing ]', users_path, class: "text-primary text-center" %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4 text-white">Edit your profile</h1>
<%= render 'edit_form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4 text-white">User profiles</h1>

<div class="flickr_pagination">
  <%= will_paginate @users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow p-0 mb-5 bg-dark rounded">
          <div class="card-header", id= "card-header">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body", id= "card-body">
            <h5 class="card-title"><%= link_to gravatar_for(user, size: 150), user %></h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <% if logged_in? %>
              <% if user == current_user %>
                <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
            <% end %>
              <% if current_user.admin? %>
                <%= link_to "Delete user", user_path(user), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure you want to delete this user and all associated articles?"} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted", id= "card-footer">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination">
  <%= will_paginate @users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/users/show.html.erb
<h1 class="text-center mt-4 text-white"><%= @user.username%>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to "Edit you profile", edit_user_path(@user), class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4 text-white">Articles</h3>

<div class="flickr_pagination">
  <%= will_paginate @articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination">
  <%= will_paginate @articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>